Repository OCA/pylint-odoo, pull requests merged in 2020-07, with the labels that each got.

#286 [REF] missing-import-error: Add new packages for Odoo v13.0
  pylint_odoo/checkers/modules_odoo.py
Labels: needs review

#287 [FIX] sql-injection: Consider valid arguments built with psycopg2.sql
  pylint_odoo/checkers/no_modules.py
  pylint_odoo/test_repo/broken_module/models/broken_model.py
Labels: need review

#288 [IMP] Add openupgradelib as a whitelist.
  pylint_odoo/checkers/modules_odoo.py
Labels: approved

#290 [ADD] duplicate-po-message-definition, po-syntax-error, po-msgstr-variables: Enable PO checks
  pylint_odoo/checkers/modules_odoo.py
  pylint_odoo/misc.py
  pylint_odoo/test/main.py
  pylint_odoo/test_repo/broken_module/i18n/es.po
  pylint_odoo/test_repo/broken_module2/i18n/en.po
  pylint_odoo/test_repo/test_module/i18n/fr.po
  requirements.txt
Labels: need review
